SCENARIO = [
    "SoundCloud",
    "Starbucks",
    "Word",
    "Internet",
    "TVING",
    "Camera",
    "Snapseed",
    "Filmora",
    "YT Music",
    "AliExpress",
    "Subway Surf",
    "Flip Diving",
    "Fit The Fat 3",
    "Asphalt 9",
    "Disney+",
    "Netflix",
    "YouTube",
    "ESPN",
    "ZARA",
    "TikTok"
]

PACKAGE = {
    "SoundCloud": "com.soundcloud.android",
    "Starbucks": "com.starbucks.co",
    "Word": "com.microsoft.office.word",
    "Internet": "com.sec.android.app.sbrowser",
    "TVING": "net.cj.cjhv.gs.tving",
    "Camera": "com.sec.android.app.camera",
    "Snapseed": "com.niksoftware.snapseed",
    "Filmora": "com.wondershare.filmorago",
    "YT Music": "com.google.android.apps.youtube.music",
    "AliExpress": "com.alibaba.aliexpresshd",
    "Subway Surf": "com.kiloo.subwaysurf",
    "Flip Diving": "com.motionvolt.flipdiving",
    "Fit The Fat 3": "com.fivebits.fitthefat3",
    "Asphalt 9": "com.gameloft.android.ANMP.GloftA9HM",
    "Disney+": "com.disney.disneyplus",
    "Netflix": "com.netflix.mediaclient",
    "YouTube": "com.google.android.youtube",
    "ESPN": "com.espn.score_center",
    "ZARA": "com.inditex.zara",
    "TikTok": "com.ss.android.ugc.trill"
}

ACTIVITY = {
    "SoundCloud": "com.soundcloud.android.onboarding.auth.AuthenticationActivity",
    "Starbucks": "com.starbucks.co2.ui.intro.IntroActivity",
    "Word": "com.microsoft.office.apphost.LaunchActivity",
    "Internet": "com.sec.android.app.sbrowser.SBrowserMainActivity",
    "TVING": "net.cj.cjhv.gs.tving.view.scaleup.ScaleupIntroActivity",
    "Camera": "com.sec.android.app.camera.Camera",
    "Snapseed": "com.google.android.apps.snapseed.WelcomeScreenActivity",
    "Filmora": "com.filmorago.phone.ui.homepage.HomePageActivityNewSinceV570",
    "YT Music": "com.google.android.apps.youtube.music.activities.MusicActivity",
    "AliExpress": "com.alibaba.aliexpresshd.home.ui.MainActivity",
    "Subway Surf": "com.sybogames.chili.multidex.ChiliMultidexSupportActivity",
    "Flip Diving": "com.unity3d.player.UnityPlayerActivity",
    "Fit The Fat 3": "com.unity3d.player.UnityPlayerActivity",
    "Asphalt 9": "com.gameloft.android.ANMP.GloftA9HM.MainActivity",
    "Disney+": "com.bamtechmedia.dominguez.main.MainActivity",
    "Netflix": "com.netflix.mediaclient.ui.launch.UIWebViewActivity",
    "YouTube": "com.google.android.apps.youtube.app.watchwhile.WatchWhileActivity",
    "ESPN": "com.espn.sportscenter.ui.EspnLaunchActivity",
    "ZARA": "com.inditex.zara.MainActivity",
    "TikTok": "com.ss.android.ugc.aweme.splash.SplashActivity"
}
